---
title: "STATS3355HW8"
author: "Udit Lal"
date: "2024-04-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Problem 1
```{r}
set.seed(1)

x <- 1:100
e <- rnorm(100, mean = 0, sd = 6)
y <- 1 + 2*x + e
data <- data.frame(x, y)

plot(data$x, data$y, main = "Scatter plot with Regression Line", xlab = "x", ylab = "y", pch = 19)
fit <- lm(y ~ x, data = data)
abline(fit, col = "red")

summary(fit)

beta1 <- coef(fit)[2]
se_beta1 <- summary(fit)$coefficients[2, 2]

t <- (beta1 - 2) / se_beta1
p <- 2 * pt(abs(t), df = length(x) - 2)

cat("t - stat", t, "\n")
cat("p - value:", p, "\n")

```

#Problem 2
```{r}
price <- c(300000, 250000, 400000, 550000, 317000, 389000, 425000, 289000, 389000)
bedrooms <- c(3, 3, 4, 5, 4, 3, 6, 3, 4)

data <- data.frame(price, bedrooms)

plot(data$bedrooms, data$price, main = "House Prices vs Bedrooms", xlab = "Bedrooms",
     ylab = "Price", pch = 19)

fit <- lm(price ~ bedrooms, data = data)
abline(fit, col = "red")

newData <- data.frame(bedrooms = seq(2, 8))
pred <- predict(fit, newdata = newData, interval = "confidence")

lines(newData$bedrooms, pred[, 2], col = "blue", lty = 2)
lines(newData$bedrooms, pred[, 3], col = "blue", lty = 2)

```

#Problem 3
```{r}
library(UsingR)
data(deflection)

fit <- lm(Deflection ~ Load, data = deflection)

plot(deflection$Load, deflection$Deflection, main = "Deflection vs. Load", xlab = "Load",
     ylab = "Deflection", pch = 19)
abline(fit, col = "red")

confint(fit)

```