---
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Problem 1

(a) finding the first on the sixth try
P(X = 6) = (1 - 1/25)^6-1 * 1/25
         = 1/25(24/25)^5
         ~ .04(.96)^5
         ~ 0.036

(b) Taking 4 tries to find the first bulb
P(X >= 4) = 1 - P(X < 4)
          = 1 - (((1-1/25)^0 * 1/25)) + (1 - (1/25)^1 * 1/25) + (1-(1/25)^2 * 1/25))
          = 1 - 1/25(1 + 24/25 + (24/25)^2)
          = 1 - 1/25(2.8816)
          = 1 - .115264
          ~ 0.885

(c) At most 10 tries
```{r}
#P(X <= 10) = P(X = 1) + P(X = 2) + ... + P(X = 10)
x <- (1-(25/24)^0) * 1/25 + (1-(25/24)^1) * 1/25 + (1-(25/24)^2) * 1/25 + (1-(25/24)^3) * 1/25 + (1-(25/24)^4) * 1/25 + (1-(25/24)^5) * 1/25 + (1-(25/24)^6) * 1/25 + (1-(25/24)^7) * 1/25 + (1-(25/24)^8) * 1/25 + (1-(25/24)^9) * 1/25 + (1-(25/24)^10) * 1/25
```

#Problem 2
```{r}
set.seed(20220707)
rolls <- replicate(10000, sum(sample(1:6, 5, replace = TRUE) == 1))
```

```{r}
library(ggplot2)
ggplot(data.frame(rolls), aes(x = rolls)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black", aes(y = ..density..)) +
  labs(title = "Histogram of Number of Ones Rolled", x = "Number of Ones Rolled", y = "Density") +
  theme_minimal()

```


```{r}
sample_mean <- mean(rolls)
print(paste("Sample mean:", round(sample_mean, 3)))
sample_variance <- var(rolls)
print(paste("Sample variance:", round(sample_variance, 3)))

```

#Problem 3
```{r}
lambda <- 180/60
congestion <- 1 - sum(dpois(0:5, lambda))
congestion <- round(congestion, 3)
print(paste("Probability of congestion occurring:", congestion))

```

```{r}
cars <- 0:10
prob <- dpois(cars, lambda)

# Create a data frame for plotting
df <- data.frame(cars = cars, prob = prob)

# Plot the bar chart
ggplot(df, aes(x = cars, y = prob)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Probability Distribution of Cars Passing in One Minute",
       x = "Number of Cars Passing",
       y = "Probability") +
  theme_minimal()

```

#Problem 4
```{r}
mean_score <- 500
sd_score <- 100

less <- pnorm(585, mean_score, sd_score)
less <- round(less, 3)

print(paste("Probability of scoring 585 or less:", less))

```

```{r}
lower<- qnorm(0.25, mean_score, sd_score)
median<- qnorm(0.5, mean_score, sd_score)
upper<- qnorm(0.75, mean_score, sd_score)

lower<- round(lower, 3)
median<- round(median, 3)
upper<- round(upper, 3)

# Display the results
print(paste("Lower-quartile:", lower))
print(paste("Median:", median))
print(paste("Upper-quartile:", upper))

```

#Problem 5
P(W) = P(W|G) * P(G) + P(W|R) * P(R)
     = (.8 * .95) + (.8 * .05)
     = .8

P(R|W) = (.8 * .05)/.8
       = .05 or 5%